# Toolchain description file for the CC65 compiler suite

set(CMAKE_SYSTEM_NAME cc65)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_CROSSCOMPILING TRUE)

# Shared libraries are not supported at all
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)

set(CMAKE_SYSTEM_PROCESSOR "6502")

if (CMAKE_TOOLCHAIN_FILE)
endif()

set(CMAKE_C_COMPILER_FORCED TRUE CACHE BOOL "")

set(CMAKE_C_COMPILER "cl65.exe" CACHE FILEPATH "CC65 compiler")
set(CMAKE_LINKER "cl65.exe" CACHE FILEPATH "CC65 linker")
set(CMAKE_AR "ar65.exe" CACHE FILEPATH "CC65 archiver")
set(CMAKE_C_COMPILER_AR "${CMAKE_AR}" CACHE FILEPATH "CC65 ar")

set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_ID cc65)
set(CMAKE_C_COMPILER_FRONTEND_VARIANT "")
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 89)

set(CMAKE_CXX_COMPILER_ID_RUN FALSE)
set(CMAKE_CXX_COMPILER_FORCED FALSE)
set(CMAKE_CXX_COMPILER_WORKS FALSE)
set(CMAKE_CXX_COMPILER_ID cc65)
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT "")
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "")

string(APPEND CMAKE_C_FLAGS_DEBUG_INIT " -g")
# Maybe we should use -Or to make register work
string(APPEND CMAKE_C_FLAGS_MINSIZEREL_INIT " -O -D NDEBUG")
string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " -O -D NDEBUG")
string(APPEND CMAKE_C_FLAGS_RELWITHDEBINFO_INIT " -O -g -D NDEBUG")

set(CMAKE_EXECUTABLE_SUFFIX "")

set(CMAKE_SKIP_COMPATIBILITY_TESTS 1)
set(CMAKE_SIZEOF_CHAR 1)
set(CMAKE_SIZEOF_UNSIGNED_SHORT 2)
set(CMAKE_SIZEOF_SHORT 2)
set(CMAKE_SIZEOF_INT 2)
set(CMAKE_SIZEOF_UNSIGNED_LONG 4)
set(CMAKE_SIZEOF_UNSIGNED_INT 2)
set(CMAKE_SIZEOF_LONG 4)
set(CMAKE_SIZEOF_VOID_P 2)
set(CMAKE_SIZEOF_FLOAT 0)
set(CMAKE_SIZEOF_DOUBLE 0)
set(CMAKE_C_SIZEOF_DATA_PTR 2)
set(CMAKE_HAVE_LIMITS_H 1)
set(CMAKE_HAVE_UNISTD_H 1)
set(CMAKE_HAVE_PTHREAD_H 0)
set(CMAKE_HAVE_SYS_PRCTL_H 0)
set(CMAKE_WORDS_BIGENDIAN 0)
set(CMAKE_DL_LIBS)

set(CMAKE_C_COMPILE_OBJECT
  "<CMAKE_C_COMPILER> -c -o <OBJECT> <DEFINES> <INCLUDES> <FLAGS> <SOURCE>")

set(CMAKE_C_LINK_EXECUTABLE
  "<CMAKE_LINKER> -o <TARGET>.c64 <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES>")
